import Foundation

// Inspirational quotes for loading screen
struct QuotesLibrary {
    static let allQuotes: [Quote] = [
        Quote(text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha", category: "manifestation"),
        Quote(text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "purpose"),
        Quote(text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "action"),
        Quote(text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "inner_strength"),
        Quote(text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "action"),
        Quote(text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi", category: "love"),
        Quote(text: "The wound is the place where the Light enters you.", author: "Rumi", category: "growth"),
        Quote(text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha", category: "mindfulness"),
        Quote(text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "resilience"),
        Quote(text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll", category: "perspective"),
        Quote(text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "action"),
        Quote(text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "courage"),
        Quote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "confidence"),
        Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "dreams"),
        Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "possibility"),
        Quote(text: "What we think, we become.", author: "Buddha", category: "mindset"),
        Quote(text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", category: "mindset"),
        Quote(text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "identity"),
        Quote(text: "Act as if what you do makes a difference. It does.", author: "William James", category: "impact"),
        Quote(text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "perseverance"),
        Quote(text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "action"),
        Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "persistence"),
        Quote(text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "imagination"),
        Quote(text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "doubt"),
        Quote(text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "hope"),
        Quote(text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "transformation"),
        Quote(text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "happiness"),
        Quote(text: "The mind is everything. What you think you become.", author: "Buddha", category: "mindset"),
        Quote(text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "presence"),
        Quote(text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "purpose"),
        Quote(text: "You only live once, but if you do it right, once is enough.", author: "Mae West", category: "living_fully"),
        Quote(text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", category: "quality_of_life"),
        Quote(text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison", category: "perseverance"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "action"),
        Quote(text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt", category: "uncertainty"),
        Quote(text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford", category: "destiny"),
        Quote(text: "In order to write about life first you must live it.", author: "Ernest Hemingway", category: "experience"),
        Quote(text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "resilience"),
        Quote(text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", category: "simplicity"),
        Quote(text: "May you live every day of your life.", author: "Jonathan Swift", category: "presence"),
        Quote(text: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen", category: "wonder"),
        Quote(text: "Do not let making a living prevent you from making a life.", author: "John Wooden", category: "balance"),
        Quote(text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard", category: "experience"),
        Quote(text: "The unexamined life is not worth living.", author: "Socrates", category: "reflection"),
        Quote(text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "growth"),
        Quote(text: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton", category: "optimism"),
        Quote(text: "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", author: "John Wesley", category: "service"),
        Quote(text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", category: "courage"),
        Quote(text: "You are enough just as you are.", author: "Meghan Markle", category: "self_worth"),
        Quote(text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "action"),
        Quote(text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "possibility"),
        Quote(text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", category: "optimism"),
        Quote(text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy", category: "inner_strength"),
        Quote(text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "growth"),
        Quote(text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "action"),
        Quote(text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", category: "transformation"),
        Quote(text: "The energy of the mind is the essence of life.", author: "Aristotle", category: "vitality"),
        Quote(text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin", category: "courage"),
        Quote(text: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn", category: "possibility"),
        Quote(text: "Your limitation—it's only your imagination.", author: "Unknown", category: "potential"),
        Quote(text: "Great things never come from comfort zones.", author: "Unknown", category: "growth"),
        Quote(text: "Dream it. Wish it. Do it.", author: "Unknown", category: "action"),
        Quote(text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown", category: "action"),
        Quote(text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown", category: "achievement"),
        Quote(text: "Dream bigger. Do bigger.", author: "Unknown", category: "ambition"),
        Quote(text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown", category: "perseverance"),
        Quote(text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown", category: "daily_practice"),
        Quote(text: "Do something today that your future self will thank you for.", author: "Unknown", category: "future_focus"),
        Quote(text: "Little things make big days.", author: "Unknown", category: "appreciation"),
        Quote(text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown", category: "determination"),
        Quote(text: "Don't wait for opportunity. Create it.", author: "Unknown", category: "proactivity"),
        Quote(text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown", category: "challenges"),
        Quote(text: "The key to success is to focus on goals, not obstacles.", author: "Unknown", category: "focus"),
        Quote(text: "Dream it. Believe it. Build it.", author: "Unknown", category: "creation"),
        Quote(text: "What lies before us and what lies behind us are small matters compared to what lies within us.", author: "Oliver Wendell Holmes", category: "inner_strength"),
        Quote(text: "Peace comes from within. Do not seek it without.", author: "Buddha", category: "inner_peace"),
        Quote(text: "The soul always knows what to do to heal itself. The challenge is to silence the mind.", author: "Caroline Myss", category: "healing"),
        Quote(text: "Gratitude turns what we have into enough.", author: "Aesop", category: "gratitude"),
        Quote(text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius", category: "gratitude"),
        Quote(text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thích Nhất Hạnh", category: "mindfulness"),
        Quote(text: "Be happy in the moment, that's enough. Each moment is all we need, not more.", author: "Mother Teresa", category: "presence"),
        Quote(text: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius", category: "mindset"),
        Quote(text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", category: "control"),
        Quote(text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius", category: "happiness"),
        Quote(text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", category: "wonder"),
        Quote(text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", category: "mindset"),
        Quote(text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", category: "living_fully"),
        Quote(text: "The only way out is through.", author: "Robert Frost", category: "perseverance"),
        Quote(text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", category: "resilience"),
        Quote(text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane", category: "presence"),
        Quote(text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller", category: "love"),
        Quote(text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", author: "Martin Luther King Jr.", category: "love"),
        Quote(text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "service"),
        Quote(text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop", category: "kindness"),
        Quote(text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank", category: "action"),
        Quote(text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", category: "love"),
        Quote(text: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett", category: "dreams"),
        Quote(text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks", category: "courage"),
        Quote(text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt", category: "renewal"),
        Quote(text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", category: "determination"),
        Quote(text: "There is nothing impossible to they who will try.", author: "Alexander the Great", category: "possibility"),
        Quote(text: "The bad news is time flies. The good news is you're the pilot.", author: "Michael Altshuler", category: "control"),
        Quote(text: "Life has got all those twists and turns. You've got to hold on tight and off you go.", author: "Nicole Kidman", category: "adventure"),
        Quote(text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt", category: "balance"),
        Quote(text: "You can waste your lives drawing lines. Or you can live your life crossing them.", author: "Shonda Rhimes", category: "boundaries"),
        Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "Malala Yousafzai", category: "possibility")
    ]
}
