import Foundation

// Comprehensive library of 150+ values with definitions
struct ValuesLibrary {
    static let allValues: [Value] = [
        Value(name: "Accountability", definition: "Taking responsibility for your actions and their consequences; being answerable to others and yourself for commitments made."),
        Value(name: "Achievement", definition: "Striving to accomplish goals and reach milestones; finding satisfaction in tangible results and success."),
        Value(name: "Adaptability", definition: "Being flexible and open to change; adjusting effectively to new circumstances and challenges."),
        Value(name: "Adventure", definition: "Seeking new experiences and embracing the unknown; finding excitement in exploration and discovery."),
        Value(name: "Ambition", definition: "Having strong desire and determination to achieve something; setting high goals and working toward them."),
        Value(name: "Authenticity", definition: "Being genuine and true to yourself; expressing your real thoughts, feelings, and values rather than conforming."),
        Value(name: "Autonomy", definition: "Having independence and self-direction; making your own choices and controlling your own life."),
        Value(name: "Balance", definition: "Maintaining equilibrium between different aspects of life; avoiding extremes and finding harmony."),
        Value(name: "Beauty", definition: "Appreciating and creating aesthetic experiences; valuing visual, artistic, or natural elegance."),
        Value(name: "Belonging", definition: "Feeling connected and accepted within a community or group; having meaningful relationships and social bonds."),
        Value(name: "Benevolence", definition: "Caring about the welfare of others; acting with kindness and goodwill toward people."),
        Value(name: "Boldness", definition: "Having courage to take risks and stand out; being willing to be different or controversial when necessary."),
        Value(name: "Calmness", definition: "Maintaining inner peace and composure; approaching situations with serenity rather than anxiety."),
        Value(name: "Caring", definition: "Showing concern and compassion for others' wellbeing; being attentive to others' needs and feelings."),
        Value(name: "Challenge", definition: "Seeking difficult tasks that test your abilities; finding motivation in overcoming obstacles."),
        Value(name: "Clarity", definition: "Pursuing clear thinking and communication; removing ambiguity and confusion from situations."),
        Value(name: "Collaboration", definition: "Working cooperatively with others toward shared goals; valuing teamwork and collective effort."),
        Value(name: "Commitment", definition: "Dedicating yourself fully to people, causes, or goals; following through on promises and obligations."),
        Value(name: "Community", definition: "Contributing to and participating in collective groups; valuing social connection and shared identity."),
        Value(name: "Compassion", definition: "Feeling deep sympathy for others' suffering and wanting to alleviate it; combining empathy with action."),
        Value(name: "Competence", definition: "Developing skill and capability in your endeavors; striving for mastery and effectiveness."),
        Value(name: "Competition", definition: "Engaging in contests or rivalries; finding motivation in measuring yourself against others."),
        Value(name: "Confidence", definition: "Believing in your abilities and judgment; approaching challenges with self-assurance."),
        Value(name: "Connection", definition: "Building deep, meaningful relationships; feeling emotionally linked to others."),
        Value(name: "Conscientiousness", definition: "Being thorough, careful, and diligent; taking duties seriously and acting responsibly."),
        Value(name: "Consistency", definition: "Being reliable and predictable in behavior; maintaining steadiness across time and situations."),
        Value(name: "Contentment", definition: "Finding satisfaction with what you have; experiencing peace and acceptance with your current state."),
        Value(name: "Contribution", definition: "Making a positive difference in the world; adding value to others' lives or to society."),
        Value(name: "Courage", definition: "Facing fear, danger, or difficulty with bravery; taking action despite uncertainty or risk."),
        Value(name: "Creativity", definition: "Generating original ideas and novel solutions; expressing imagination and innovation."),
        Value(name: "Curiosity", definition: "Having a strong desire to learn and explore; asking questions and seeking understanding."),
        Value(name: "Dependability", definition: "Being reliable and trustworthy; consistently doing what you say you'll do."),
        Value(name: "Determination", definition: "Persisting despite obstacles; maintaining firmness of purpose and resolve."),
        Value(name: "Dignity", definition: "Treating yourself and others with respect and worth; maintaining self-respect regardless of circumstances."),
        Value(name: "Diligence", definition: "Working carefully and persistently; showing steady, earnest effort in your endeavors."),
        Value(name: "Discipline", definition: "Controlling your impulses and maintaining focus; following through with rules and routines."),
        Value(name: "Discovery", definition: "Finding new knowledge, places, or experiences; enjoying the process of learning and uncovering."),
        Value(name: "Diversity", definition: "Valuing differences in people, ideas, and approaches; embracing variety and inclusion."),
        Value(name: "Efficiency", definition: "Accomplishing tasks with minimal waste of time or resources; optimizing processes and efforts."),
        Value(name: "Empathy", definition: "Understanding and sharing the feelings of others; seeing situations from others' perspectives."),
        Value(name: "Empowerment", definition: "Enabling yourself and others to take control; building confidence and capability in people."),
        Value(name: "Endurance", definition: "Persisting through long-term challenges; having stamina and staying power."),
        Value(name: "Energy", definition: "Bringing vitality and enthusiasm to activities; maintaining high levels of vigor and drive."),
        Value(name: "Enjoyment", definition: "Finding pleasure and fun in experiences; prioritizing activities that bring joy."),
        Value(name: "Enthusiasm", definition: "Showing intense interest and excitement; approaching life with passion and zeal."),
        Value(name: "Equality", definition: "Treating all people as having equal worth and rights; opposing discrimination and hierarchy."),
        Value(name: "Excellence", definition: "Pursuing the highest quality in everything; refusing to settle for mediocre results."),
        Value(name: "Excitement", definition: "Seeking stimulation and thrilling experiences; valuing activities that create arousal and energy."),
        Value(name: "Exploration", definition: "Investigating new territories, ideas, or possibilities; pushing beyond familiar boundaries."),
        Value(name: "Fairness", definition: "Treating people equitably and justly; applying consistent standards without favoritism."),
        Value(name: "Faith", definition: "Having trust and belief in something greater than yourself; maintaining conviction without complete proof."),
        Value(name: "Family", definition: "Prioritizing close relatives and chosen kin; valuing familial bonds and obligations."),
        Value(name: "Fearlessness", definition: "Acting without being paralyzed by fear; confronting intimidating situations directly."),
        Value(name: "Fidelity", definition: "Being faithful and loyal to commitments, people, or principles; maintaining constancy."),
        Value(name: "Flexibility", definition: "Adapting easily to changes; avoiding rigid thinking or behavior patterns."),
        Value(name: "Focus", definition: "Concentrating attention on priorities; avoiding distraction and maintaining clear direction."),
        Value(name: "Forgiveness", definition: "Letting go of resentment and anger; offering pardon to yourself and others."),
        Value(name: "Freedom", definition: "Having liberty to act, think, and choose; being unrestricted by excessive external control."),
        Value(name: "Friendship", definition: "Building and maintaining close personal relationships; valuing companionship and mutual support."),
        Value(name: "Frugality", definition: "Using resources carefully and avoiding waste; living within or below your means."),
        Value(name: "Fun", definition: "Engaging in playful, enjoyable activities; prioritizing lightheartedness and entertainment."),
        Value(name: "Generosity", definition: "Giving freely of your time, resources, or energy; being liberal and openhanded."),
        Value(name: "Gentleness", definition: "Being mild, tender, and kind in manner; avoiding harshness or roughness."),
        Value(name: "Grace", definition: "Moving through life with elegance and dignity; responding to situations with poise."),
        Value(name: "Gratitude", definition: "Feeling and expressing thankfulness; appreciating what you have and what others do."),
        Value(name: "Growth", definition: "Continuously developing and improving yourself; evolving beyond your current state."),
        Value(name: "Happiness", definition: "Pursuing joy and positive emotional states; prioritizing wellbeing and life satisfaction."),
        Value(name: "Harmony", definition: "Seeking peaceful coexistence and compatibility; avoiding conflict and discord."),
        Value(name: "Health", definition: "Maintaining physical, mental, and emotional wellbeing; prioritizing your body's needs."),
        Value(name: "Helpfulness", definition: "Assisting others and being of service; offering aid and support readily."),
        Value(name: "Honesty", definition: "Telling the truth and being straightforward; refusing to deceive or mislead."),
        Value(name: "Honor", definition: "Acting with integrity and adhering to ethical principles; maintaining reputation and respect."),
        Value(name: "Hope", definition: "Maintaining optimism about the future; believing positive outcomes are possible."),
        Value(name: "Humility", definition: "Being modest and avoiding arrogance; recognizing your limitations and others' contributions."),
        Value(name: "Humor", definition: "Finding and creating amusement; approaching life with levity and the ability to laugh."),
        Value(name: "Independence", definition: "Being self-reliant and not needing others' approval; functioning autonomously."),
        Value(name: "Individuality", definition: "Expressing your unique identity; celebrating what makes you different from others."),
        Value(name: "Innovation", definition: "Creating new methods, ideas, or products; driving change through invention."),
        Value(name: "Inquisitiveness", definition: "Asking questions and seeking deeper understanding; being intellectually curious and probing."),
        Value(name: "Integrity", definition: "Living according to your values consistently; having strong moral principles and honesty."),
        Value(name: "Intelligence", definition: "Valuing mental capability and using reason; pursuing knowledge and understanding."),
        Value(name: "Intimacy", definition: "Building deep emotional closeness with others; sharing vulnerability and authentic connection."),
        Value(name: "Intuition", definition: "Trusting your instincts and inner knowing; making decisions based on gut feelings."),
        Value(name: "Joy", definition: "Experiencing and spreading intense happiness; finding delight in life's moments."),
        Value(name: "Justice", definition: "Ensuring fair treatment and consequences; advocating for what is right and equitable."),
        Value(name: "Kindness", definition: "Being considerate, generous, and friendly; treating others with warmth and care."),
        Value(name: "Knowledge", definition: "Acquiring information and understanding; valuing education and intellectual development."),
        Value(name: "Leadership", definition: "Guiding and inspiring others toward goals; taking responsibility for direction and vision."),
        Value(name: "Learning", definition: "Continuously acquiring new skills and information; remaining a lifelong student."),
        Value(name: "Legacy", definition: "Creating lasting impact beyond your lifetime; building something that endures."),
        Value(name: "Leisure", definition: "Valuing free time and relaxation; making space for rest and recreational activities."),
        Value(name: "Love", definition: "Feeling and expressing deep affection; caring intensely for others' wellbeing and happiness."),
        Value(name: "Loyalty", definition: "Remaining faithful to people, organizations, or causes; standing by commitments through difficulty."),
        Value(name: "Mastery", definition: "Achieving expert-level skill; pursuing excellence and deep competence in areas of focus."),
        Value(name: "Meaning", definition: "Finding purpose and significance in life; ensuring activities align with deeper values."),
        Value(name: "Mindfulness", definition: "Being present and aware in the current moment; paying attention without judgment."),
        Value(name: "Moderation", definition: "Avoiding excess and maintaining reasonable limits; finding the middle path."),
        Value(name: "Modesty", definition: "Being unassuming and humble; avoiding showiness or excessive pride."),
        Value(name: "Open-mindedness", definition: "Considering new ideas and perspectives; avoiding prejudgment and rigid thinking."),
        Value(name: "Openness", definition: "Being transparent and receptive; sharing honestly and welcoming others' input."),
        Value(name: "Optimism", definition: "Maintaining a positive outlook; expecting favorable outcomes and focusing on possibilities."),
        Value(name: "Order", definition: "Creating and maintaining organization; having structure and systematic approaches."),
        Value(name: "Originality", definition: "Being unique and unconventional; creating things that are novel and distinctly yours."),
        Value(name: "Passion", definition: "Feeling intense enthusiasm and emotion; being deeply invested in what matters to you."),
        Value(name: "Patience", definition: "Accepting delays without frustration; maintaining calm and composure while waiting."),
        Value(name: "Peace", definition: "Seeking tranquility and absence of conflict; valuing serenity internally and externally."),
        Value(name: "Perseverance", definition: "Continuing despite difficulty or opposition; refusing to give up on important goals."),
        Value(name: "Playfulness", definition: "Approaching life with spontaneity and fun; not taking everything seriously."),
        Value(name: "Positivity", definition: "Focusing on the good in situations; maintaining an upbeat and constructive attitude."),
        Value(name: "Power", definition: "Having influence and control over outcomes; being able to affect change and make impact."),
        Value(name: "Pragmatism", definition: "Being practical and realistic; focusing on what works rather than ideals alone."),
        Value(name: "Precision", definition: "Being exact and accurate; paying attention to details and avoiding errors."),
        Value(name: "Preparedness", definition: "Planning ahead and being ready; anticipating needs and potential challenges."),
        Value(name: "Presence", definition: "Being fully engaged in the current moment; giving complete attention to what's happening now."),
        Value(name: "Pride", definition: "Taking satisfaction in achievements and identity; maintaining self-respect and dignity."),
        Value(name: "Privacy", definition: "Protecting personal boundaries and information; maintaining control over your private life."),
        Value(name: "Productivity", definition: "Accomplishing tasks efficiently and effectively; generating meaningful output and results."),
        Value(name: "Professionalism", definition: "Maintaining high standards in work; behaving competently and appropriately in professional settings."),
        Value(name: "Prosperity", definition: "Achieving success and flourishing in all areas of life; experiencing abundance and thriving conditions."),
        Value(name: "Purpose", definition: "Having clear direction and meaning; knowing why you do what you do."),
        Value(name: "Quality", definition: "Prioritizing excellence over quantity; ensuring high standards in outputs and experiences."),
        Value(name: "Rationality", definition: "Using logic and reason; making decisions based on evidence and clear thinking."),
        Value(name: "Recognition", definition: "Being acknowledged for your contributions; receiving appreciation and validation from others."),
        Value(name: "Reflection", definition: "Thinking deeply about experiences and yourself; engaging in introspection and contemplation."),
        Value(name: "Reliability", definition: "Being consistently dependable; following through on commitments regularly."),
        Value(name: "Resilience", definition: "Bouncing back from setbacks; recovering quickly from difficulties and adapting."),
        Value(name: "Resourcefulness", definition: "Finding creative solutions with available means; overcoming obstacles through ingenuity."),
        Value(name: "Respect", definition: "Treating others with consideration and regard; honoring people's worth and boundaries."),
        Value(name: "Responsibility", definition: "Being accountable for duties and obligations; taking ownership of your role and actions."),
        Value(name: "Restraint", definition: "Exercising self-control; avoiding impulsive or excessive behavior."),
        Value(name: "Risk-taking", definition: "Willingly exposing yourself to uncertainty; trying things despite potential negative outcomes."),
        Value(name: "Safety", definition: "Protecting yourself and others from harm; prioritizing security and avoiding danger."),
        Value(name: "Security", definition: "Having stability and freedom from threats; maintaining a safe foundation in life."),
        Value(name: "Self-awareness", definition: "Understanding your own thoughts, feelings, and motivations; recognizing your patterns and impact."),
        Value(name: "Self-care", definition: "Attending to your own needs and wellbeing; prioritizing activities that restore and nourish you."),
        Value(name: "Self-control", definition: "Managing impulses and emotions; directing your behavior through willpower."),
        Value(name: "Self-expression", definition: "Communicating your authentic self; sharing your thoughts, feelings, and creativity freely."),
        Value(name: "Self-reliance", definition: "Depending on your own capabilities; being able to function independently."),
        Value(name: "Self-respect", definition: "Valuing and honoring yourself; maintaining dignity and positive self-regard."),
        Value(name: "Service", definition: "Contributing to others' wellbeing; dedicating effort to helping and supporting."),
        Value(name: "Significance", definition: "Making a meaningful impact; being important or influential in some way."),
        Value(name: "Simplicity", definition: "Reducing complexity and excess; focusing on essentials and avoiding complications."),
        Value(name: "Sincerity", definition: "Being genuine and honest in expression; meaning what you say without pretense."),
        Value(name: "Solitude", definition: "Valuing time alone; finding peace and renewal in your own company."),
        Value(name: "Spirituality", definition: "Connecting with something transcendent; exploring meaning beyond the material world."),
        Value(name: "Spontaneity", definition: "Acting on impulse and in the moment; being flexible and unpredictable."),
        Value(name: "Stability", definition: "Maintaining consistency and reliability; avoiding unnecessary change or chaos."),
        Value(name: "Status", definition: "Achieving recognition and social standing; being respected and admired by others."),
        Value(name: "Stewardship", definition: "Taking care of resources and responsibilities entrusted to you; managing with long-term thinking."),
        Value(name: "Strength", definition: "Possessing physical, mental, or emotional power; having capacity to endure and overcome."),
        Value(name: "Structure", definition: "Creating frameworks and systems; organizing life with clear rules and boundaries."),
        Value(name: "Success", definition: "Achieving desired outcomes and goals; reaching milestones others recognize as accomplishments."),
        Value(name: "Support", definition: "Providing help and encouragement to others; being there when people need you."),
        Value(name: "Sustainability", definition: "Acting with long-term viability in mind; ensuring resources and systems can continue."),
        Value(name: "Teamwork", definition: "Collaborating effectively with others; contributing to collective success."),
        Value(name: "Temperance", definition: "Exercising moderation and self-restraint; avoiding excess in all things."),
        Value(name: "Tenacity", definition: "Holding firmly to goals and convictions; refusing to let go despite challenges."),
        Value(name: "Thoughtfulness", definition: "Being considerate and reflective; thinking carefully about impacts and meanings."),
        Value(name: "Thrift", definition: "Using resources economically; getting maximum value while spending minimally."),
        Value(name: "Tradition", definition: "Honoring customs and established practices; maintaining connection to cultural heritage."),
        Value(name: "Tranquility", definition: "Experiencing calm and peace; living without anxiety or turbulence."),
        Value(name: "Transparency", definition: "Being open and clear in communication; operating without hidden agendas."),
        Value(name: "Trust", definition: "Having confidence in others' reliability; believing in integrity and keeping promises."),
        Value(name: "Trustworthiness", definition: "Being worthy of others' confidence; demonstrating reliability and honesty consistently."),
        Value(name: "Truth", definition: "Seeking and speaking what is accurate and real; prioritizing facts over convenience."),
        Value(name: "Understanding", definition: "Comprehending deeply and empathizing; seeing beyond surface to grasp full context."),
        Value(name: "Uniqueness", definition: "Embracing what makes you different; celebrating distinctive qualities and perspectives."),
        Value(name: "Unity", definition: "Creating cohesion and oneness; bringing people or elements together harmoniously."),
        Value(name: "Versatility", definition: "Adapting to various roles and situations; having diverse capabilities and flexibility."),
        Value(name: "Victory", definition: "Achieving wins and overcoming opposition; succeeding in competitive endeavors."),
        Value(name: "Vigor", definition: "Bringing physical and mental energy; approaching life with vitality and intensity."),
        Value(name: "Vision", definition: "Seeing possibilities for the future; having clear, inspiring ideas about what could be."),
        Value(name: "Vitality", definition: "Living with energy and aliveness; feeling vibrant and fully engaged in life."),
        Value(name: "Warmth", definition: "Showing affection and friendliness; creating comfort and positive emotional atmosphere."),
        Value(name: "Wealth", definition: "Having abundant financial resources; accumulating material prosperity."),
        Value(name: "Wisdom", definition: "Applying knowledge with good judgment; understanding deep truths about life and people."),
        Value(name: "Wonder", definition: "Experiencing awe and amazement; maintaining childlike curiosity about the world."),
        Value(name: "Zeal", definition: "Having intense enthusiasm and dedication; pursuing goals with passionate fervor.")
    ]
}
